-- Seed system skills (read-only, shared across all users)
-- Only insert if not already present (idempotent)

INSERT INTO "skills" ("key", "name", "description", "files", "is_system", "user_id", "org_id")
SELECT 'web-research', 'Web Research', 'Search the web and extract content from URLs for research tasks',
  '[{"path":"SKILL.md","content":"# Web Research Skill\n\nUse this skill to research topics on the web by searching and extracting content from URLs.\n\n## Available Tools\n\n- **webSearch**: Search the web for information on any topic\n- **extractContent**: Extract readable content from a web page URL\n- **fetch**: Fetch raw content from a URL (for APIs, data files, etc.)\n\n## Workflow\n\n1. **Search**: Use `webSearch` to find relevant sources\n   ```\n   webSearch --query \"your search terms\"\n   ```\n\n2. **Extract**: Use `extractContent` to read full articles\n   ```\n   extractContent --url \"https://example.com/article\"\n   ```\n\n3. **Synthesize**: Combine information from multiple sources\n\n## Best Practices\n\n- Use specific, targeted search queries\n- Cross-reference information from multiple sources\n- Cite your sources when presenting findings\n- Use extractContent for articles, fetch for raw data/APIs\n"},{"path":"references/search-tips.md","content":"# Search Tips\n\n## Effective Search Queries\n\n- **Be specific**: Use precise terms rather than generic ones\n- **Use quotes**: Wrap exact phrases in quotes (\"exact phrase\")\n- **Include year**: Add the year for recent information (e.g., \"React 2024\")\n- **Site-specific**: Use site:example.com to search within a site\n\n## Query Examples\n\n| Goal | Query |\n|------|-------|\n| Recent docs | \"Next.js 14 documentation 2024\" |\n| Specific error | \"TypeError cannot read property undefined React\" |\n| Comparisons | \"PostgreSQL vs MySQL performance 2024\" |\n| Tutorials | \"how to implement OAuth2 Node.js tutorial\" |\n\n## When to Use Each Tool\n\n- **webSearch**: Finding sources, getting an overview\n- **extractContent**: Reading full articles, documentation\n- **fetch**: APIs, JSON data, raw files\n"}]'::jsonb,
  true, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM "skills" WHERE "key" = 'web-research' AND "is_system" = true);
--> statement-breakpoint

INSERT INTO "skills" ("key", "name", "description", "files", "is_system", "user_id", "org_id")
SELECT 'document-management', 'Document Management', 'Create, read, update, and search documents/artifacts',
  '[{"path":"SKILL.md","content":"# Document Management Skill\n\nManage documents (artifacts) - create, read, update, and search.\n\n## Available Tools\n\n- **writeArtifact**: Create a new document\n- **readArtifact**: Read an existing document by ID\n- **searchArtifacts**: Search documents by title/content\n- **updateArtifact**: Update an existing document\n\n## Common Operations\n\n### Create a Document\n```\nwriteArtifact --title \"Meeting Notes\" --content \"# Meeting Notes\\n\\n...\" --summary \"Notes from team sync\"\n```\n\n### Search Documents\n```\nsearchArtifacts --query \"meeting notes\"\n```\n\n### Read a Document\n```\nreadArtifact --artifactId \"uuid-here\"\n```\n\n### Update a Document\n```\nupdateArtifact --artifactId \"uuid-here\" --content \"Updated content...\"\n```\n\n## Best Practices\n\n- Use descriptive titles for easy searching\n- Include a summary for quick reference\n- Use markdown formatting for structure\n- Search before creating to avoid duplicates\n"}]'::jsonb,
  true, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM "skills" WHERE "key" = 'document-management' AND "is_system" = true);
--> statement-breakpoint

INSERT INTO "skills" ("key", "name", "description", "files", "is_system", "user_id", "org_id")
SELECT 'project-management', 'Project Management', 'Create and manage projects and tasks with Kanban boards',
  '[{"path":"SKILL.md","content":"# Project Management Skill\n\nManage projects and tasks using a Kanban-style board system.\n\n## Project Tools\n\n- **listProjects**: List all projects\n- **searchProjects**: Search projects by name\n- **getProject**: Get project details\n- **createProject**: Create a new project\n- **updateProject**: Update project details\n- **deleteProject**: Delete a project\n\n## Task Tools\n\n- **listTasks**: List tasks in a project\n- **searchTasks**: Search tasks across projects\n- **getTask**: Get task details\n- **createTask**: Create a new task\n- **updateTask**: Update task details\n- **deleteTask**: Delete a task\n- **moveTask**: Move task to different status\n- **reorderTask**: Reorder task within status column\n- **attachArtifactToTask**: Link a document to a task\n- **detachArtifactFromTask**: Unlink a document from a task\n\n## Workflow Example\n\n### 1. Create a Project\n```\ncreateProject --title \"Website Redesign\" --summary \"Q1 website refresh\"\n```\n\n### 2. Add Tasks\n```\ncreateTask --projectId \"uuid\" --title \"Design mockups\" --priority \"high\"\ncreateTask --projectId \"uuid\" --title \"Implement header\" --priority \"medium\"\n```\n\n### 3. Track Progress\n```\nmoveTask --taskId \"uuid\" --status \"in_progress\"\nmoveTask --taskId \"uuid\" --status \"done\"\n```\n"},{"path":"references/task-states.md","content":"# Task States\n\n## Status Values\n\n| Status | Description |\n|--------|-------------|\n| backlog | Not yet scheduled |\n| todo | Ready to start |\n| in_progress | Currently being worked on |\n| review | Ready for review |\n| done | Completed |\n\n## Priority Values\n\n| Priority | When to Use |\n|----------|-------------|\n| low | Nice to have, no deadline |\n| medium | Standard work items |\n| high | Important, needs attention soon |\n| urgent | Critical, needs immediate attention |\n\n## State Transitions\n\nTypical flow:\n```\nbacklog → todo → in_progress → review → done\n```\n\nTasks can move backwards if needed (e.g., review → in_progress for revisions).\n"},{"path":"references/workflow.md","content":"# Project Workflow\n\n## Starting a New Project\n\n1. **Create the project** with a clear title and summary\n2. **Break down work** into individual tasks\n3. **Prioritize tasks** (urgent → high → medium → low)\n4. **Move tasks through states** as work progresses\n\n## Task Best Practices\n\n- **One task per unit of work**: Keep tasks focused and achievable\n- **Clear titles**: Should describe what needs to be done\n- **Add descriptions**: Include context, acceptance criteria\n- **Link documents**: Attach relevant artifacts to tasks\n\n## Daily Workflow\n\n1. Check tasks in \"todo\" status\n2. Move task to \"in_progress\" when starting\n3. Move to \"review\" when ready for feedback\n4. Move to \"done\" when complete\n"}]'::jsonb,
  true, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM "skills" WHERE "key" = 'project-management' AND "is_system" = true);
--> statement-breakpoint

INSERT INTO "skills" ("key", "name", "description", "files", "is_system", "user_id", "org_id")
SELECT 'agent-management', 'Agent Management', 'List, configure, and spawn other agents',
  '[{"path":"SKILL.md","content":"# Agent Management Skill\n\nManage and interact with other agents in the system.\n\n## Available Tools\n\n- **listAgents**: List all available agents\n- **getAgent**: Get detailed info about an agent\n- **updateAgent**: Update agent configuration\n- **setAgentEnabled**: Enable or disable an agent\n- **toggleAgentFavorite**: Mark agent as favorite\n- **spawnAgent**: Spawn another agent to handle a subtask\n\n## Listing Agents\n```\nlistAgents\nlistAgents --type \"server\" --includeDisabled true\n```\n\n## Spawning Agents\n\nUse spawnAgent to delegate tasks to specialized agents:\n```\nspawnAgent --agentId \"researcher\" --message \"Research the latest React 19 features\"\n```\n\n### When to Spawn\n\n- Task requires specialized knowledge\n- Need parallel processing\n- Want a fresh context for a subtask\n- Delegating to domain experts\n\n### Spawn Best Practices\n\n- Provide clear, complete instructions\n- Include all necessary context in the message\n- Spawned agents don''t have your conversation history\n"}]'::jsonb,
  true, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM "skills" WHERE "key" = 'agent-management' AND "is_system" = true);
--> statement-breakpoint

INSERT INTO "skills" ("key", "name", "description", "files", "is_system", "user_id", "org_id")
SELECT 'utilities', 'Utilities', 'General utilities like time and UI navigation',
  '[{"path":"SKILL.md","content":"# Utilities Skill\n\nGeneral-purpose utilities for time and UI interaction.\n\n## Available Tools\n\n- **getTime**: Get current date and time\n- **navigateTo**: Navigate the user''s browser to a path\n- **getCurrentUIState**: Get current page info\n\n## Time Operations\n```\ngetTime\ngetTime --timezone \"America/New_York\"\n```\n\n## Navigation\n\nNavigate the user to specific pages:\n```\nnavigateTo --path \"/app/projects\"\nnavigateTo --path \"/app/artifacts\"\nnavigateTo --path \"/app/agents\"\n```\n\n## UI State\n\nCheck what page the user is currently viewing:\n```\ngetCurrentUIState\n```\n\nReturns current path, page title, and route parameters.\n"}]'::jsonb,
  true, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM "skills" WHERE "key" = 'utilities' AND "is_system" = true);
